const notes = [
  {
    id: 1,
    title: 'Why so serious?',
    body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?',
    date: 'Mon, 12 Jan',
    favorite: false,
    highlight: true,
  },
  {
    id: 2,
    title: 'Make me laugh',
    body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae.',
    date: 'Thur, 12 Oct',
    favorite: false,
    highlight: false,
  },
  {
    id: 3,
    title: 'Breaking Bad',
    body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis.',
    date: 'Wed, 22 Sep',
    favorite: true,
    highlight: false,
  },
  {
    id: 4,
    title: 'What happen to Roll num 21?',
    body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?',
    date: 'Tue, 2 June',
    favorite: false,
    highlight: true,
  },
  {
    id: 5,
    title: 'What happen to Roll num 21?',
    body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente earum porro laboriosam quas, iste saepe dolorem sunt, ullam reiciendis quibusdam beatae tempora exercitationem dolorum, sit cum tenetur blanditiis debitis? Nemo?',
    date: 'Tue, 2 June',
    favorite: false,
    highlight: false,
  },
];
